### ISSUE TITLE
Replace the worldmap with dex909's high quality version

### ISSUE THREAD

**Issue by skellytz** [SpellholdStudios/BGT-WeiDU#11]
[Here](http://www.shsforums.net/topic/57463-german-multilanguage-version-of-bg2-soa-same-as-usuk-ver/#entry577773) is what it looks like. I'll expand the "Baldur's G." banner to fit "Gate" in there too.

Good idea to replace the stock BP-BGT worldmap? Should it also replace the smaller ToB map?

**Comment by Gitjas** [comment]
I can't answer to the questions but this looks really cool! Thank you for your work on this!

**Comment by weigo87** [comment]
You can make like BP-BGT-Worldmap an extra component to replace the smaller ToB map. So everyone has the choice.
One small thing, the banner behind the Baldurs Gate Label is to small.

**Comment by skellytz** [comment]
This should probably be part of BP-BGT Worldmap.
