### ISSUE TITLE
Setup can't find tis2bg2 on linux

### ISSUE THREAD

**Issue by burner1024** [SpellholdStudios/BGT-WeiDU#12]
```
[areaw500/AR1500HT.BMP] created from [bgt/bg1/DATA/AREA1500.BIF]
[areaw500/AR1500LM.BMP] created from [bgt/bg1/DATA/AREA1500.BIF]
[areaw500/AR1500SR.BMP] created from [bgt/bg1/DATA/AREA1500.BIF]
Copying and patching 1 file ...
Copying 1 file ...



Converting tilesets...
/bin/sh: 1: bgt/install/unix/amd64/tis2bg2: not found
/bin/sh: 1: bgt/install/unix/amd64/tis2bg2: not found
/bin/sh: 1: bgt/install/unix/amd64/tis2bg2: not found
/bin/sh: 1: bgt/install/unix/amd64/tis2bg2: not found
...
```

At first I though it's a permission problem, but they are correct:
```
# ls -l bgt/install/unix/amd64/tis2bg2
-rwxr-xr-x 1 user user 17956 Dec 14 23:48 bgt/install/unix/amd64/tis2bg2
```
My guess is $PWD is wrong for some reason... but I can't find it.

More importantly, installation doesn't fail on this.

Edit: oh wait, I'm stupid. Apparently it's still [32 bit](https://github.com/SpellholdStudios/BGT-WeiDU/issues/4) in the last release?
```
./bgt/install/unix/amd64/tis2bg2
-su: ./bgt/install/unix/amd64/tis2bg2: No such file or directory
```

**Comment by skellytz** [comment]
That's right, the 64-bit versions of these binaries have only recently been created by Roberciiik (thanks again!).

**Comment by burner1024** [comment]
I see. Still, would be good to have an extra error check in case it fails to run.

**Comment by burner1024** [comment]
I see that the binaries have been added, but still, for more foolproof installation I would really recommend to actually check exit code of the conversion tools.

**Comment by skellytz** [comment]
Yes, later I'll see what I can do about that.
