### ISSUE TITLE
Wrong music is played.

### ISSUE THREAD

**Issue by Whosondephone** [SpellholdStudios/BGT-WeiDU#16]
I've noticed that the music in the temple is the same as in the taverns.  The only reason I know this is wrong because I breafly played through unmodified Baldurs Gate Original Saga.  I'm thinking other places might have wrong music too as indicated in 
[this forum thread.](http://www.shsforums.net/topic/57069-bgtmusic-issues/) 

I'm a compleat n00b following [this guide.](https://www.gog.com/forum/baldurs_gate_series/baldurs_gate_2_essential_mods/page1) 

I'm going to try again because it looks like I used bgt-v1.20 with bg2fixpack-v13.exe

Could the nocd patch be causing trouble?

I'm going to try reinstalling again.

**Comment by Gitjas** [comment]
As described in the documentation, you need to install the BGT Music Pack (setup-bgtmusic.exe) after the main BGT installation.

**Comment by Gitjas** [comment]
(Without the BGT Music Pack, this is normale behavior. This issue can be closed.)

**Comment by Whosondephone** [comment]
Thank you for the quick responce.  I am certain I installed the music pack.  However I'm combing through the instructions an noticed my version of original Saga 1.3.5521 not 5512.

**Comment by Whosondephone** [comment]
After a very complicated install across 3 OS's it seems to be working now on my win98 rig after speaking out all of the latest versions of the mods Thanks Again!  You guys Rock!

**Comment by Gitjas** [comment]
Great! And apologies, I should have asked whether you installed the BGT Music Pack, first. But tavern music is what happens if the music pack is not installed, so I jumped to conclusions.
