### ISSUE TITLE
Creature rare selection sounds

### ISSUE THREAD

**Issue by skellytz** [SpellholdStudios/BGT-WeiDU#17]
This was intended to be a component of Infinity Sounds, but I'd like to include it in BGT core. Good idea?

> In BG1, creatures have four rare selection slots which, if present, typically play tongue-in-cheek lines after the player (right)-clicks the given creature nine consecutive times. The BG2 engine treats these soundset offsets differently making them effectively unavailable. The only way to restore the sounds is to move them to the common selection slots, which also removes the nine-click trigger condition.

**Comment by burner1024** [comment]
What's "effectively unavailable"? Is there a specific example?

**Comment by skellytz** [comment]
In BG1 CRE soundset offsets 0x130 - 0x13c are rare selection sounds (both PC and NPC), but in BG2 engine these are treated as action sounds (played when issuing orders to PCs). That's why currently in BGT you won't hear eg "never let thy warrior shoot the foot" when you right-click a tutor in Candlekeep nine times.

**Comment by skellytz** [comment]
This will remain a component of Infinity Sounds.
