### ISSUE TITLE
Feature Request - allow supplying path to bg1 install via .txt file

### ISSUE THREAD

**Issue by peterhoeg** [SpellholdStudios/BGT-WeiDU#22]
The Tweaks-Anthology supports providing responses to questions via variables defined in a text file: https://github.com/Gibberlings3/Tweaks-Anthology/blob/master/cdtweaks/cdtweaks.disabled.txt

It would be great if we could do the same for bgt so it could run completely unattended.

**Comment by skellytz** [comment]
Please check the auto-installation section of the [readme](https://spellholdstudios.github.io/readmes/bgt/%5Benglish%5Dbgtreadme.htm).
