### ISSUE TITLE
Revise BG1 map labels

### ISSUE THREAD

**Issue by skellytz** [SpellholdStudios/BGT-WeiDU#5]
BGT arbitrarily changes some area labels and adds new non-canon names. I believe the original labels should be restored to remain faithful to the classic BG1TotSC. Any new labels should be considered tweaks (eg [Sword Coast Map Labels](http://www.shsforums.net/topic/46634-sword-coast-map-labels/) by Miloch).

Any thoughts or suggestions?

Restored original BG1TotSC map labels:
  * [x] English
  * [x] Czech
  * [x] French
  * [x] German
  * [x] Italian
  * [x] Korean
  * [x] Polish
  * [x] Russian
  * [x] Spanish
  * [x] Simplified Chinese
  * [x] Traditional Chinese

**Comment by Roberciiik** [comment]
I agree with you, it could be removed as some names are really confusing. Possibly, extra labels could be an optional component during an installation.

**Comment by skellytz** [comment]
I honestly think both BGT and Dudleyville extra labels are inaccurate, inconsistent and include spoilers. In my view, they hardly qualify even for an optional component. Sword Coast Map Labels does a slightly better job and will still be available to players who want all BG1 areas labeled.

**Comment by Gitjas** [comment]
I like this idea, too. Thank you for your work!
