### ISSUE TITLE
Gorion missing audio

### ISSUE THREAD

**Issue by jeyerman** [SpellholdStudios/BGT-WeiDU#56]
Gorion has the following line during the cutscene in Lion's Way: "Let's hurry child! The night can only get worse so we must find shelter soon. Don't worry, I'll explain everything as soon as there is time." The associated audio file is GORIN11.wav. In the original Baldur's Gate, the associated audio plays during the cutscene, however in BGT it does not.

Interestingly, in the original Baldur's Gate, this text is associated with two strrefs according to NI:  #2910 and #4446. Strref #4446 is associated with GORIN11.wav, whereas #2910 is not associated with any audio file.

In BGT, the associated strrefs are #4446 and #80288, and neither is associated with GORIN11.wav. I have found that if I manually create the association with strref #4446 with GORIN11.wav via NI, the audio clip plays as it should during the cutscene.

**Comment by skellytz** [comment]
This is a bug in BG2 Fixpack game text update, not BGT. Already reported on [Gibberlings3 forums](https://www.gibberlings3.net/forums/topic/29719-the-new-fixpack-thread-for-compatibility-bug-reporting-changingremoving-fixes/?do=findComment&comment=267820).
