### ISSUE TITLE
Balduran's Log Book not salable

### ISSUE THREAD

**Issue by HunterZ** [SpellholdStudios/BGT-WeiDU#60]
Looking at BG1/TotSC in Near Infinity shows that Balduran's Log Book is categorized as Gems with a value of 10,000 GP. This seems to be an intentional choice by the developers to allow it to be sold to vendors.

BGT-WeiDU seems to have changed it to the Books category, which while logically more consistent now makes it impossible to sell because there is literally nobody who buys books!

I will also note that BG1 EE seems to have retained the ability to sell this item, but has apparently reduced its value to 5,000 GP.

**Comment by skellytz** [comment]
This wasn't changed by BGT but by BG2 devs. As typically is the case, if a given file is already present in BG2, BGT doesn't overwrite it with the BG1 version and uses the BG2 one. Some files were patched to restore certain features from BG1, but that required a lot of busy work checking everything and there may be several files like this that went unnoticed.

Restoring the gems category. Thanks!
