### ISSUE TITLE
Familiar has SoA stats when cast during BG1

### ISSUE THREAD

**Issue by majcosta** [SpellholdStudios/BGT-WeiDU#69]
Expected to get 6 extra HP, got 12 instead. Assuming Pseudodragon has 24 HP as well.

![image](https://github.com/SpellholdStudios/BGT-WeiDU/assets/34732933/61adac71-7b3e-4c4e-a4a2-40559689f9d0)

**Comment by Salk73** [comment]
I don't understand why you expected to get 6 hit points. BGT's familiars are those that come in SoA and ToB. You are getting the less powerful of the two, there is no BG1 familiar.

May I recommend trying [my WTP Familiars modification](http://forums.blackwyrmlair.net/index.php?showtopic=5278), if you want to experience Familiars properly in BGT?

**Comment by majcosta** [comment]
huh, you are right. I'm closing this.
